### ISSUE TITLE
Determining the identifier

### ISSUE THREAD

**Issue by MacBucky** [timsutton/mcxToProfile#15]
Hi Guys,

I am trying to use mcxToProfile for the first time and it seems to make sense.  I am having a tough time understanding the identifier component that is needed.  For instance, I want to take the com.apple.dock.plist and set it once for a lab of Macs.

Using this I am getting an error saying: no such option --identifier

I guess I am really foggy about what is needed and how the identifier is determined and used.

Thank you, Mick

**Comment by timsutton** [comment]
`--identifier` is a name of your own choosing. If you want to use this to build a lab dock profile, your identifier could be "LabDock". (Spaces are probably allowed, too)

**Comment by MacBucky** [comment]
Thanks for the quick reply Tim.  Do you know if sudo is required?

**Comment by timsutton** [comment]
`sudo` is not required (and shouldn't be used) to run this tool, but if you are installing the profile via a command line interactively, it would be required if you want the profile to take effect for all users. But there are plenty of other ways to install a profile as well.

**Comment by MacBucky** [comment]
Awesome.  I think I have it working.  Thank you so much for the quick replies....

**Comment by timsutton** [comment]
No problem.
