### ISSUE TITLE
How can I get this to run on macos 12.4

### ISSUE THREAD

**Issue by bigben386** [timsutton/mcxToProfile#21]
Hi,
I used this app multiple times in the past to create mobileconfig files. I am not a macos or python expert. Now that my macbook has updated to macos 12, I cannot get this script to run. I assume it has to do with python 2 being removed in favor of python 3. I fixed the first issue with this script by changing the print options line to print(option...) but now I am getting this error
raceback (most recent call last):
  File "./mcxToProfile.py", line 13, in <module>
    from Foundation import NSData, \
ModuleNotFoundError: No module named 'Foundation'

pip3 and python help('modules') shows the package foundation is installed (not Foundation). I tried changing the code to foundation but it doesnt work either. I also tried using pyenv to run the script in python 2.7 but i can't seem to get that to work either. Any help is appreciated.
Thanks

**Comment by kcrawford** [comment]
Foundation is part of pyobjc so make sure you are using a python3 that includes that like macadmins python on GitHub.

Kyle

**Comment by bigben386** [comment]
That did the trick with the original script. Thanks for pointing me in the right direction.
