### ISSUE TITLE
-dsobject only returns payload for the first MCX preference domain

### ISSUE THREAD

**Issue by dayglojesus** [timsutton/mcxToProfile#3]
Performing an operation like...

./mcxToProfile.py --dsobject /LDAPv3/foo.bar.org/ComputerGroups/this_group --identifier org.bar.foo.this_group

Against an object with one or more MCX preference domains specified...

com.apple.loginwindow
com.apple.homeSync
com.apple.mcxMenuExtras
com.apple.MCX

Will produce a .mobileconfig with a single policy payload -- AFAICT just the first domain (maybe the last if it is reversing the order) that gets processed.

**Comment by alifkifi** [comment]
ali
